# Generated by Django 5.2.7 on 2025-11-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge_app', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='email',
            field=models.EmailField(default='info@nalalahouse.com', max_length=254),
        ),
    ]
